---
# 机场订阅
proxy-providers:
  VPS:
    # 订阅方式
    type: http
    # 订阅链接
    url: "订阅链接"
    # 更新时间：1天
    interval: 86400
    # 监控检测
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://www.gstatic.com/generate_204
    # 订阅获取：直连获取
    proxy: 直连
    # 该订阅请求头
    # header:
    #   User-Agent:
    #     - "Clash"
    #     - "mihomo"
    #     - "Clash.meta"
    override:
      udp: true
      skip-cert-verify: true

  MM:
    type: http
    url: "订阅链接"
    interval: 86400
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://www.gstatic.com/generate_204
    proxy: 直连
    override:
      udp: true
      skip-cert-verify: true

  6B:
    type: http
    url: "订阅链接"
    interval: 86400
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://www.gstatic.com/generate_204
    proxy: 直连
    override:
      udp: true
      skip-cert-verify: true

# 节点信息
proxies:

# 全局配置
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
allow-lan: true
external-controller: 0.0.0.0:9090
secret: R4XBrm5n
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
external-ui-name: metacubexd
keep-alive-interval: 15
keep-alive-idle: 600
ipv6: false
geox-url:
  mmdb: https://testingcf.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/lite/Country.mmdb
  geoip: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  asn: https://testingcf.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb
sniffer:
  enable: true
  override-destination: true
  sniff:
    QUIC:
      ports:
      - 443
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - dlg.io.mi.com
  - "+.oray.com"
  - "+.sunlogin.net"
  - "+.push.apple.com"
  parse-pure-ip: true
profile:
  store-selected: true
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: false
  respect-rules: true
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - "+.lan"
  - "+.local"
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - time.*.com
  - xiaomi.com
  - "+.xiaomi.com"
  - "+.pool.ntp.org"
  - geosite:cn
  proxy-server-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 8.8.8.8
  - 1.1.1.1
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
rule-providers:
  "\U0001F310 代理域名_PlanetEditorX":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/PlanetEditorX/subconverter/refs/heads/main/custom/ProxyDomain.list
    path: "./rule_provider/ProxyDomain.list"
    interval: 86400
    format: text
  "\U0001F6D1 广告拦截_ACL4SSR":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: "./rule_provider/BanAD.list"
    interval: 86400
    format: text
  "\U0001F6D1 广告拦截_PlanetEditorX":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/PlanetEditorX/subconverter/refs/heads/main/custom/CustomProhibit.list
    path: "./rule_provider/CustomProhibit.list"
    interval: 86400
    format: text
  "\U0001F343 应用净化":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    path: "./rule_provider/BanProgramAD.list"
    interval: 86400
    format: text
  "\U0001F18E AdBlock_EasyList":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
    path: "./rule_provider/BanEasyList.list"
    interval: 86400
    format: text
  "\U0001F18E AdBlock_EasyListChina":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
    path: "./rule_provider/BanEasyListChina.list"
    interval: 86400
    format: text
  "\U0001F6E1️ 隐私防护":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
    path: "./rule_provider/BanEasyPrivacy.list"
    interval: 86400
    format: text
  "\U0001F916 AI服务_PlanetEditorX":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/PlanetEditorX/subconverter/refs/heads/main/custom/ChatGPT.list
    path: "./rule_provider/ChatGPT.list"
    interval: 86400
    format: text
  "\U0001F4F1 Tiktok":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
    path: "./rule_provider/TikTok.list"
    interval: 86400
    format: text
  "\U0001F3AF 全球直连_DirectDomain":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/PlanetEditorX/subconverter/refs/heads/main/custom/DirectDomain.list
    path: "./rule_provider/DirectDomain.list"
    interval: 86400
    format: text
  "\U0001F3AF 全球直连_DirectIP":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/PlanetEditorX/subconverter/refs/heads/main/custom/DirectIP.list
    path: "./rule_provider/DirectIP.list"
    interval: 86400
    format: text
  "✈️ 机场连接_Sub":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/PlanetEditorX/subconverter/refs/heads/main/custom/AirportIP.list
    path: "./rule_provider/AirportIP.list"
    interval: 86400
    format: text
  "✈️ 机场连接_Free":
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/PlanetEditorX/subconverter/refs/heads/main/custom/FreeAirportIP.list
    path: "./rule_provider/FreeAirportIP.list"
    interval: 86400
    format: text
  "\U0001F3AF 全球直连_CustomDirect":
    type: http
    behavior: classical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct.list
    path: "./rule_provider/Custom_Direct.list"
    interval: 28800
    format: text
  "\U0001F3AF 全球直连_SteamCDN":
    type: http
    behavior: classical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Steam_CDN.list
    path: "./rule_provider/Steam_CDN.list"
    interval: 28800
    format: text
proxy-groups:
- name: "\U0001F680 节点选择"
  type: select
  proxies:
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F452 霉霉机场"
  - "\U0001F42E 牛逼机场"
  - "\U0001F680 手动选择"
  - "\U0001F381 免费节点"
  - DIRECT
- name: "\U0001F680 手动选择"
  type: select
  use:
      - VPS
      - MM
      - 6B
- name: "☯︎ 智能选择"
  type: smart
  include-all: true
  url: https://www.gstatic.com/generate_204
  interval: 300
  policy-priority: v5:2;G口:1.8;hk:1.5;香港:1.5;sg:1.4;新加坡:1.4;日本:1;jp:1;台湾:0.9;tw:0.9;v4:0.8;阿根廷:0.3;ipv6:0.3;FREE-*:0.1
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
  exclude-filter: "(?i)FREE-.*"
- name: "\U0001F1ED\U0001F1F0 香港智能"
  type: smart
  include-all: true
  filter: "(港|HK|hk|Hong Kong|HongKong|hongkong|深港)"
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
  exclude-filter: "(?i)FREE-.*"
- name: "\U0001F1F8\U0001F1EC 狮城智能"
  type: smart
  include-all: true
  filter: "(新加坡|坡|狮城|SG|Singapore)"
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
  exclude-filter: "(?i)FREE-.*"
- name: "\U0001F1FA\U0001F1F2 美国智能"
  type: smart
  include-all: true
  filter: "(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|ChatGPT|chatgpt)"
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
  exclude-filter: "(?i)FREE-.*"
- name: "\U0001F525 VPS节点"
  type: smart
  include-all: true
  filter: "(VPS)"
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
  exclude-filter: "(?i)FREE-.*"
- name: "\U0001F517 链式代理"
  type: smart
  use:
    - VPS
- name: "\U0001F4AC Telegram"
  type: select
  proxies:
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "☯︎ 智能选择"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F680 手动选择"
- name: "\U0001F680 GitHub"
  type: select
  proxies:
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F680 手动选择"
  - "\U0001F381 免费节点"
  - "\U0001F3AF 全球直连"
- name: "\U0001F916 AI服务"
  type: select
  proxies:
  - "\U0001F1FA\U0001F1F2 美国智能"
  - "☯︎ 智能选择"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F310 其他地区"
  - "\U0001F381 免费节点"
  - "\U0001F680 手动选择"
- name: "\U0001F310 代理域名"
  type: select
  proxies:
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F452 霉霉机场"
  - "\U0001F42E 牛逼机场"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F381 免费节点"
  - "\U0001F680 节点选择"
  - "\U0001F680 手动选择"
- name: "\U0001F4F9 YouTube"
  type: select
  proxies:
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F310 其他地区"
  - "\U0001F381 免费节点"
  - "\U0001F680 手动选择"
- name: "\U0001F1EC 谷歌服务"
  type: select
  proxies:
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "☯︎ 智能选择"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
- name: "\U0001F30E 国外媒体"
  type: select
  proxies:
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F310 其他地区"
  - "\U0001F381 免费节点"
  - "\U0001F680 手动选择"
  - "\U0001F3AF 全球直连"
- name: "\U0001F381 免费节点"
  type: smart
  include-all: true
  filter: "(FREE)"
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: false
  strategy: sticky-sessions
- name: "\U0001F41F 漏网之鱼"
  type: select
  proxies:
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F680 节点选择"
  - "\U0001F680 手动选择"
  - "\U0001F381 免费节点"
  - "\U0001F3AF 全球直连"
- name: "\U0001F3C6 优选节点"
  type: smart
  proxies:
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
- name: "\U0001F452 霉霉机场"
  type: smart
  use:
      - MM
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
  exclude-filter: "(?i)FREE-.*"
- name: "\U0001F42E 牛逼机场"
  type: smart
  use:
      - 6B
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
  exclude-filter: "(?i)FREE-.*"
- name: "\U0001F4F1 Tiktok"
  type: select
  proxies:
  - "\U0001F3AF 全球直连"
  - "\U0001F1FA\U0001F1F2 美国智能"
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F680 手动选择"
  - "\U0001F381 免费节点"
- name: "\U0001F6D2 国外电商"
  type: select
  proxies:
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F310 其他地区"
  - "\U0001F680 手动选择"
  - "\U0001F3AF 全球直连"
- name: "\U0001F4E2 谷歌FCM"
  type: select
  proxies:
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "☯︎ 智能选择"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F310 其他地区"
  - "\U0001F680 手动选择"
  - "\U0001F3AF 全球直连"
- name: "\U0001F34E 苹果服务"
  type: select
  proxies:
  - "\U0001F3AF 全球直连"
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F680 手动选择"
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - "\U0001F3AF 全球直连"
  - "☯︎ 智能选择"
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F680 手动选择"
  - REJECT
- name: "\U0001F310 社交媒体"
  type: select
  proxies:
  - "\U0001F1ED\U0001F1F0 香港智能"
  - "☯︎ 智能选择"
  - "\U0001F1F8\U0001F1EC 狮城智能"
  - "\U0001F1E8\U0001F1F3 台湾智能"
  - "\U0001F1EF\U0001F1F5 日本智能"
  - "\U0001F517 链式代理"
  - "\U0001F525 VPS节点"
  - "\U0001F680 手动选择"
- name: "\U0001F3AE 游戏平台"
  type: select
  proxies:
  - "\U0001F3AF 全球直连"
  - "\U0001F680 手动选择"
- name: "\U0001F3AE Steam"
  type: select
  proxies:
  - "\U0001F3AF 全球直连"
  - "\U0001F680 手动选择"
- name: "\U0001F680 测速工具"
  type: select
  proxies:
  - "\U0001F3AF 全球直连"
  - "\U0001F680 手动选择"
- name: "✈️ 机场连接"
  type: select
  proxies:
  - DIRECT
  - "\U0001F680 节点选择"
- name: "\U0001F6D1 广告拦截"
  type: select
  proxies:
  - REJECT
- name: "\U0001F343 应用净化"
  type: select
  proxies:
  - REJECT
- name: "\U0001F18E AdBlock"
  type: select
  proxies:
  - REJECT
- name: "\U0001F6E1️ 隐私防护"
  type: select
  proxies:
  - REJECT
- name: "\U0001F1EF\U0001F1F5 日本智能"
  type: smart
  include-all: true
  filter: "(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|JP|Japan|\U0001F1EF\U0001F1F5)"
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
- name: "\U0001F1E8\U0001F1F3 台湾智能"
  type: smart
  include-all: true
  filter: "(台|新北|彰化|TW|Taiwan)"
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
- name: "\U0001F310 其他地区"
  type: smart
  include-all: true
  filter: "^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|深港|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United
    States|UnitedStates|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|JP|Japan|\U0001F1EF\U0001F1F5|新加坡|坡|狮城|SG|Singapore|台|新北|彰化|TW|Taiwan|KR|Korea|KOR|首尔|韩|韓)).*"
  url: https://www.gstatic.com/generate_204
  interval: 300
  uselightgbm: true
  collectdata: true
  strategy: sticky-sessions
- name: "\U0001F3AF 全球直连"
  type: select
  proxies:
  - DIRECT
  - "\U0001F680 手动选择"
rules:
- GEOSITE,category-public-tracker,DIRECT
- "RULE-SET,\U0001F310 代理域名_PlanetEditorX,\U0001F310 代理域名"
- "RULE-SET,\U0001F6D1 广告拦截_ACL4SSR,\U0001F6D1 广告拦截"
- "RULE-SET,\U0001F6D1 广告拦截_PlanetEditorX,\U0001F6D1 广告拦截"
- "RULE-SET,\U0001F343 应用净化,\U0001F343 应用净化"
- "RULE-SET,\U0001F18E AdBlock_EasyList,\U0001F18E AdBlock"
- "RULE-SET,\U0001F18E AdBlock_EasyListChina,\U0001F18E AdBlock"
- "RULE-SET,\U0001F6E1️ 隐私防护,\U0001F6E1️ 隐私防护"
- "RULE-SET,\U0001F4F1 Tiktok,\U0001F4F1 Tiktok"
- "GEOSITE,youtube,\U0001F4F9 YouTube"
- "GEOSITE,category-entertainment,\U0001F30E 国外媒体"
- "RULE-SET,\U0001F916 AI服务_PlanetEditorX,\U0001F916 AI服务"
- "GEOSITE,bing,\U0001F916 AI服务"
- "GEOSITE,openai,\U0001F916 AI服务"
- "GEOSITE,category-ai-!cn,\U0001F916 AI服务"
- RULE-SET,✈️ 机场连接_Sub,✈️ 机场连接
- RULE-SET,✈️ 机场连接_Free,✈️ 机场连接
- "GEOSITE,private,\U0001F3AF 全球直连"
- "GEOIP,private,\U0001F3AF 全球直连"
- "RULE-SET,\U0001F3AF 全球直连_CustomDirect,\U0001F3AF 全球直连"
- "RULE-SET,\U0001F3AF 全球直连_DirectDomain,\U0001F3AF 全球直连"
- "RULE-SET,\U0001F3AF 全球直连_DirectIP,\U0001F3AF 全球直连"
- "GEOSITE,google-cn,\U0001F3AF 全球直连"
- "GEOSITE,category-games@cn,\U0001F3AF 全球直连"
- "RULE-SET,\U0001F3AF 全球直连_SteamCDN,\U0001F3AF 全球直连"
- "GEOSITE,category-game-platforms-download,\U0001F3AF 全球直连"
- "GEOSITE,category-public-tracker,\U0001F3AF 全球直连"
- "GEOSITE,category-communication,\U0001F4AC Telegram"
- "GEOSITE,category-social-media-!cn,\U0001F310 社交媒体"
- "GEOSITE,github,\U0001F680 GitHub"
- "GEOSITE,category-speedtest,\U0001F680 测速工具"
- "GEOSITE,steam,\U0001F3AE 游戏平台"
- "GEOSITE,apple,\U0001F34E 苹果服务"
- GEOSITE,microsoft,Ⓜ️ 微软服务
- "GEOSITE,googlefcm,\U0001F4E2 谷歌FCM"
- "GEOSITE,google,\U0001F1EC 谷歌服务"
- "GEOSITE,category-games,\U0001F3AE 游戏平台"
- "GEOSITE,category-ecommerce,\U0001F6D2 国外电商"
- "GEOIP,telegram,\U0001F4AC Telegram"
- "GEOIP,twitter,\U0001F310 社交媒体"
- "GEOIP,facebook,\U0001F310 社交媒体"
- "GEOIP,google,\U0001F1EC 谷歌服务"
- "GEOSITE,cn,\U0001F3AF 全球直连"
- "GEOIP,cn,\U0001F3AF 全球直连"
- "GEOSITE,gfw,\U0001F310 代理域名"
- PROCESS-NAME,aria2c,DIRECT
- PROCESS-NAME,BitComet,DIRECT
- PROCESS-NAME,fdm,DIRECT
- PROCESS-NAME,NetTransport,DIRECT
- PROCESS-NAME,qbittorrent,DIRECT
- PROCESS-NAME,Thunder,DIRECT
- PROCESS-NAME,transmission-daemon,DIRECT
- PROCESS-NAME,transmission-qt,DIRECT
- PROCESS-NAME,uTorrent,DIRECT
- PROCESS-NAME,WebTorrent,DIRECT
- PROCESS-NAME,Folx,DIRECT
- PROCESS-NAME,Transmission,DIRECT
- PROCESS-NAME,WebTorrent Helper,DIRECT
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,ssr-local,DIRECT
- PROCESS-NAME,ss-redir,DIRECT
- PROCESS-NAME,ssr-redir,DIRECT
- PROCESS-NAME,ss-server,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,hysteria,DIRECT
- PROCESS-NAME,singbox,DIRECT
- PROCESS-NAME,UUBooster,DIRECT
- PROCESS-NAME,uugamebooster,DIRECT
- "DST-PORT,80,\U0001F41F 漏网之鱼"
- "DST-PORT,443,\U0001F41F 漏网之鱼"
- MATCH,DIRECT