name: Update Rules List

on:
  workflow_dispatch:  # 手动触发工作流
  schedule:
    - cron: '0 0 * * *'  # 每天执行一次，或者根据需要调整

jobs:
  update-chatgpt-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Download the AI Domains List
        run: |
          curl -L https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.list -o ai-domains.list

      - name: Process Domains
        run: |
          # 为每一行加上 DOMAIN-SUFFIX, 前缀
          sed 's/^/DOMAIN-SUFFIX,/g' ai-domains.list > processed-domains.list
          cat processed-domains.list
          # 将修改后的文件移动到目标目录
          mv processed-domains.list subconverter/custom/Chatgpt.list

      - name: Commit Changes
        run: |
          # 提交更新
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add subconverter/custom/Chatgpt.list
          git commit -m "Update Chatgpt.list with AI domains"
          git push
